// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using OrdersApi.Infrastructure.StorageProviders.SqlServer.EventStorage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace OrdersApi.Infrastructure.Migrations
{
    [DbContext(typeof(SqlEventStorageContext))]
    [ExcludeFromCodeCoverage]
    partial class SqlEventStorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrdersApi.Infrastructure.StorageProviders.SqlServer.EventStorage.EventData", b =>
                {
                    b.Property<string>("EventKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(25)");

                    b.Property<string>("AggregateKey")
                        .IsRequired()
                        .HasColumnType("char(25)");

                    b.Property<string>("ApplicationKey")
                        .IsRequired()
                        .HasColumnType("char(25)");

                    b.Property<byte>("ClassVersion")
                        .HasColumnType("tinyint");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasColumnType("char(32)");

                    b.Property<DateTime>("EventCommittedTimestamp")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Payload")
                        .IsRequired();

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.Property<short>("TargetVersion")
                        .HasColumnType("smallint");

                    b.Property<byte>("TimesSent")
                        .HasColumnType("tinyint");

                    b.HasKey("EventKey");

                    b.HasIndex("AggregateKey");

                    b.HasIndex("ApplicationKey", "CorrelationKey")
                        .IsUnique();

                    b.ToTable("EventData");
                });
#pragma warning restore 612, 618
        }
    }
}
